name: 'Run gremlins unleash'
description: 'Official Version Action for Gremlins'
author: 'gremlins'
inputs:
  version: # change this
    required: false
    description: 'The version of Gremlins to use'
    default: 'latest'
  args:
    required: false
    description: 'The args to pass to the unleash command'
  workdir:
    required: false
    description: 'The working directory where Gremlins will find the Go module'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: blue
  icon: box